User.create!(email: "a@a.com", password: "121212")
Post.create!(user_id: 1)
Comment.create!(user_id:1, post_id: 1)
Like.create!(name: "Like")
CommentUserLike.create!(user_id: 1, comment_id: 1, like_id: 1)
